### ISSUE TITLE
有两只伊利亚重复了

### ISSUE THREAD

**Issue by yuuki-nya** [SonderXiaoming/login_bonus#1]
![QQ图片20220727163259](https://user-images.githubusercontent.com/47957260/181200976-fb635676-f1be-4440-829a-91c453037449.png)

**Comment by SonderXiaoming** [comment]
（这锅得赖整理资源的人）我回头修一下

**Comment by SonderXiaoming** [comment]
已解决

**Comment by SonderXiaoming** [comment]
只要git pull 并且删除stamp中的27或者28任意一个
